[workspace]
resolver = "2"

members = [
    "loadlibrary",
    "server",
    "ai_bridge",
    "mahjong_core",
    "game_lib",
    "proc_macros",
    "sample",
    "app"
]

# [profile.release]
# debug = true
